version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake test
      - run: bundle exec rubocop
